{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "governance-service.fullname" . }}
  labels:
    {{- include "governance-service.labels" . | nindent 4 }}
data:
  SERVER_PORT: "{{ .Values.service.port }}"
  SERVER_READ_TIMEOUT_SECONDS: "{{ .Values.config.server.readTimeout }}"
  SERVER_WRITE_TIMEOUT_SECONDS: "{{ .Values.config.server.writeTimeout }}"
  SERVER_IDLE_TIMEOUT_SECONDS: "{{ .Values.config.server.idleTimeout }}"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  INDICATORS_CONFIG_PATH: "{{ .Values.config.indicators.configPath }}"
  INDICATORS_RELOAD_INTERVAL_SECONDS: "{{ .Values.config.indicators.reloadInterval }}"
{{- end }}
