# Enablement Check
{{- if and .Values.global.secrets.create (eq .Values.global.secrets.auth.provider "auth0") }}

# Data Validation
{{- if not .Values.global.secrets.auth.auth0.secretName }}
  {{- fail "global.secrets.auth.auth0.secretName is required when auth provider is auth0 and create is true" }}
{{- end }}
{{- if not .Values.global.secrets.auth.auth0.values.clientId }}
  {{- fail "global.secrets.auth.auth0.values.clientId is required when auth provider is auth0 and create is true" }}
{{- end }}
{{- if not .Values.global.secrets.auth.auth0.values.clientSecret }}
  {{- fail "global.secrets.auth.auth0.values.clientSecret is required when auth provider is auth0 and create is true" }}
{{- end }}
{{- if not .Values.global.secrets.auth.auth0.values.mgmtClientId }}
  {{- fail "global.secrets.auth.auth0.values.mgmtClientId is required when auth provider is auth0 and create is true" }}
{{- end }}
{{- if not .Values.global.secrets.auth.auth0.values.mgmtClientSecret }}
  {{- fail "global.secrets.auth.auth0.values.mgmtClientSecret is required when auth provider is auth0 and create is true" }}
{{- end }}

# Secret Resource
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.auth.auth0.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.global.secrets.auth.auth0.keys.clientId }}: {{ .Values.global.secrets.auth.auth0.values.clientId | quote }}
  {{ .Values.global.secrets.auth.auth0.keys.clientSecret }}: {{ .Values.global.secrets.auth.auth0.values.clientSecret | quote }}
  {{ .Values.global.secrets.auth.auth0.keys.mgmtClientId }}: {{ .Values.global.secrets.auth.auth0.values.mgmtClientId | quote }}
  {{ .Values.global.secrets.auth.auth0.keys.mgmtClientSecret }}: {{ .Values.global.secrets.auth.auth0.values.mgmtClientSecret | quote }}
{{- end }}
