{{- if .Values.global.secrets.createSecrets }}
{{- if .Values.global.secrets.values.authService.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.authServiceKeysSecretName | default "auth-service-keys" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-studio.labels" . | nindent 4 }}
type: Opaque
data:
  private-key: {{ .Values.global.secrets.values.authService.privateKey | b64enc | quote }}
{{- end }}
{{- end }}
