# Enablement Check
{{- if and .Values.global.secrets.create .Values.global.secrets.storage.aws_s3.values.accessKeyId .Values.global.secrets.storage.aws_s3.values.secretAccessKey }}

# Data Validation
{{- if not .Values.global.secrets.storage.aws_s3.secretName }}
  {{- fail "global.secrets.storage.aws_s3.secretName is required when creating AWS credentials secret" }}
{{- end }}

# Secret Resource
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.storage.aws_s3.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.global.secrets.storage.aws_s3.keys.accessKeyId }}: {{ .Values.global.secrets.storage.aws_s3.values.accessKeyId | quote }}
  {{ .Values.global.secrets.storage.aws_s3.keys.secretAccessKey }}: {{ .Values.global.secrets.storage.aws_s3.values.secretAccessKey | quote }}
{{- end }}
