# Enablement Check
{{- if .Values.global.secrets.create }}

# Data Validation
{{- if not .Values.global.secrets.database.secretName }}
  {{- fail "global.secrets.database.secretName is required when create is true" }}
{{- end }}
{{- if not .Values.global.secrets.database.values.username }}
  {{- fail "global.secrets.database.values.username is required when create is true" }}
{{- end }}
{{- if not .Values.global.secrets.database.values.password }}
  {{- fail "global.secrets.database.values.password is required when create is true" }}
{{- end }}

# Secret Resource
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.database.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Standard keys (used by platform services)
  {{ .Values.global.secrets.database.keys.username }}: {{ .Values.global.secrets.database.values.username | quote }}
  {{ .Values.global.secrets.database.keys.password }}: {{ .Values.global.secrets.database.values.password | quote }}
{{- end }}
