{{- if .Values.global.secrets.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.governanceServiceAISecretName  }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-studio.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.secrets.values.governanceService.aiApiKey }}
  ai-api-key: {{ .Values.global.secrets.values.governanceService.aiApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
