# Enablement Check
{{- if and .Values.global.secrets.create (index .Values "governance-service" "enabled") (index .Values "governance-service" "config" "serviceAccount" "enabled") }}

# Data Validation
{{- if not .Values.global.secrets.governanceWorker.secretName }}
  {{- fail "global.secrets.governanceWorker.secretName is required when governance-service.config.serviceAccount.enabled is true and create is true" }}
{{- end }}
{{- if not .Values.global.secrets.governanceWorker.values.encryptionKey }}
  {{- fail "global.secrets.governanceWorker.values.encryptionKey is required when governance-service.config.serviceAccount.enabled is true and create is true" }}
{{- end }}
{{- if not .Values.global.secrets.governanceWorker.values.clientId }}
  {{- fail "global.secrets.governanceWorker.values.clientId is required when governance-service.config.serviceAccount.enabled is true and create is true" }}
{{- end }}
{{- if not .Values.global.secrets.governanceWorker.values.clientSecret }}
  {{- fail "global.secrets.governanceWorker.values.clientSecret is required when governance-service.config.serviceAccount.enabled is true and create is true" }}
{{- end }}

# Secret Resource
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.governanceWorker.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.global.secrets.governanceWorker.keys.encryptionKey }}: {{ .Values.global.secrets.governanceWorker.values.encryptionKey | quote }}
  {{ .Values.global.secrets.governanceWorker.keys.clientId }}: {{ .Values.global.secrets.governanceWorker.values.clientId | quote }}
  {{ .Values.global.secrets.governanceWorker.keys.clientSecret }}: {{ .Values.global.secrets.governanceWorker.values.clientSecret | quote }}
{{- end }}
