# Enablement Check
{{- if .Values.global.secrets.create }}

# Data Validation
{{- if not .Values.global.secrets.imageRegistry.secretName }}
  {{- fail "global.secrets.imageRegistry.secretName is required when create is true" }}
{{- end }}
{{- if not .Values.global.secrets.imageRegistry.registry }}
  {{- fail "global.secrets.imageRegistry.registry is required when create is true" }}
{{- end }}
{{- if not .Values.global.secrets.imageRegistry.values.username }}
  {{- fail "global.secrets.imageRegistry.values.username is required when create is true" }}
{{- end }}
{{- if not .Values.global.secrets.imageRegistry.values.password }}
  {{- fail "global.secrets.imageRegistry.values.password is required when create is true" }}
{{- end }}

# Variable Assignment
{{- $registry := .Values.global.secrets.imageRegistry.registry }}
{{- $username := .Values.global.secrets.imageRegistry.values.username }}
{{- $password := .Values.global.secrets.imageRegistry.values.password }}
{{- $email := .Values.global.secrets.imageRegistry.values.email }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}

# Secret Resource
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.imageRegistry.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-platform.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{
    printf
      "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}"
      $registry
      $username
      $password
      $email
      $auth
    | b64enc
  }}
{{- end }}
