apiVersion: v2
name: governance-platform
description: A Helm chart for the complete Governance Studio platform.
type: application
version: 1.2.0

# This is the version number of the application being deployed.
appVersion: "1.0.0"

dependencies:
  - name: governance-service
    version: "1.3.3"
    repository: "file://../governance-service" # Local file system reference
    condition: governance-service.enabled

  - name: integrity-service
    version: "1.1.5"
    repository: "file://../integrity-service" # Local file system reference
    condition: integrity-service.enabled

  - name: postgresql
    version: "~12.5.5" # Bitnami chart version
    repository: "https://charts.bitnami.com/bitnami"
    alias: postgresql
    condition: postgresql.enabled

  - name: governance-studio
    version: "1.1.0"
    repository: "file://../governance-studio"
    condition: governance-studio.enabled

  - name: auth-service
    version: "1.0.4"
    repository: "file://../auth-service"
    condition: auth-service.enabled
