apiVersion: v2
name: auth-service
description: A Helm chart for deploying the EQTY Lab Auth Service - the authentication and authorization backbone
type: application
version: 1.1.1
appVersion: "1.1.1"
home: https://github.com/eqtylab/governance-studio-infrastructure
sources:
  - https://github.com/eqtylab/governance-studio-infrastructure/tree/main/charts/auth-service
maintainers:
  - name: EQTY Lab
    email: support@eqtylab.io
