{{- if and .Values.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "governance-studio.fullname" . }}
  labels:
    {{- include "governance-studio.labels" . | nindent 4 }}
spec:
  {{- if gt (int .Values.replicaCount) 1 }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "governance-studio.selectorLabels" . | nindent 6 }}
{{- end }}
