{{- if and .Values.enabled .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "governance-studio.fullname" . }}
  labels:
    {{- include "governance-studio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "governance-studio.selectorLabels" . | nindent 4 }}
{{- end }}
